import { NextResponse } from "next/server";
import { verifyRole } from "@/lib/dal";
import * as XLSX from "xlsx";

export async function GET() {
  await verifyRole(["ADMIN", "TAS"]);

  const headers = [
    // Identitas utama
    "NIS",
    "No. Induk",
    "NISN",
    "NIK",
    "Nama Lengkap",
    "Nama Panggilan",
    "Jenis Kelamin (L/P)",
    "Tempat Lahir",
    "Tanggal Lahir (DD/MM/YYYY)",
    "Agama",
    "Kewarganegaraan",
    "Anak Ke",
    "Jumlah Saudara Kandung",
    "Jumlah Saudara Tiri",
    "Jumlah Saudara Angkat",
    "Yatim/Piatu (Tidak/Yatim/Piatu/Yatim Piatu)",
    "Bahasa Sehari-hari",
    // Tempat tinggal
    "Dusun/Lingkungan",
    "RT",
    "RW",
    "Desa/Kelurahan",
    "Kecamatan",
    "Kabupaten/Kota",
    "No. HP Siswa",
    "No. HP Orang Tua",
    "Tinggal Dengan",
    "Jarak ke Sekolah",
    // Kesehatan
    "Golongan Darah (A/B/AB/O)",
    "Penyakit yang Pernah Diderita",
    "Tinggi Badan (cm)",
    "Berat Badan (kg)",
    // Asal sekolah
    "Asal Sekolah (SMP/MTs)",
    "Alamat Asal Sekolah",
    "Nomor Ijazah",
    // Masuk sekolah
    "Kode Jurusan (TKJ/AK/ATU/DKV/DPIB)",
    "Tahun Masuk",
    "Tanggal Diterima (DD/MM/YYYY)",
    // Orang tua ayah
    "Nama Ayah",
    "NIK Ayah",
    "Tempat Lahir Ayah",
    "Tanggal Lahir Ayah (DD/MM/YYYY)",
    "Pendidikan Ayah",
    "Pekerjaan Ayah",
    // Orang tua ibu
    "Nama Ibu",
    "NIK Ibu",
    "Tempat Lahir Ibu",
    "Tanggal Lahir Ibu (DD/MM/YYYY)",
    "Pendidikan Ibu",
    "Pekerjaan Ibu",
    // Wali
    "Nama Wali",
    "Pekerjaan Wali",
    // Status
    "Status (AKTIF/LULUS/KELUAR/PINDAH)",
    "Keterangan",
  ];

  const contoh = [
    "2025001",
    "953/009.1.4.1",
    "0091635504",
    "3510202710090003",
    "Arkana Keandri Haritz Cahyono",
    "Arkana",
    "L",
    "Banyuwangi",
    "27/10/2009",
    "Islam",
    "Indonesia",
    "1",
    "1",
    "0",
    "0",
    "Tidak",
    "Jawa",
    "Gantung",
    "RT/01",
    "RW/01",
    "Gendoh",
    "Sempu",
    "Banyuwangi",
    "085174336016",
    "082139934498",
    "Orang Tua",
    "Lebih Dari 1 Km",
    "O",
    "",
    "169",
    "43",
    "SMP Negeri Manba'ul Falah",
    "Jl. KH Rofii Makhsum No.25 Kemiri - Singojuruh",
    "",
    "DPIB",
    "2025",
    "14/07/2025",
    "Hari Cahyono",
    "3510201011850011",
    "Banyuwangi",
    "10/11/1985",
    "Tamat SMA Sederajat",
    "Wiraswasta",
    "Isroniyah",
    "3510206310830004",
    "Banyuwangi",
    "23/10/1983",
    "Tamat SMA Sederajat",
    "Ibu Rumah Tangga",
    "Hari Cahyono",
    "Wiraswasta",
    "AKTIF",
    "",
  ];

  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.aoa_to_sheet([headers, contoh]);
  ws["!cols"] = headers.map((h) => ({ wch: Math.max(h.length + 2, 18) }));
  XLSX.utils.book_append_sheet(wb, ws, "Buku Induk Siswa");

  const petunjukData = [
    ["PETUNJUK PENGISIAN BUKU INDUK SISWA"],
    [""],
    ["Kolom", "Keterangan", "Wajib?"],
    ["NIS", "Nomor Induk Siswa (unik, kunci data)", "Ya"],
    ["No. Induk", "Nomor buku induk sekolah", "Opsional"],
    ["NISN", "Nomor Induk Siswa Nasional", "Opsional"],
    ["NIK", "Nomor Induk Kependudukan siswa", "Opsional"],
    ["Nama Lengkap", "Nama lengkap sesuai akte", "Ya"],
    ["Nama Panggilan", "Nama sehari-hari", "Opsional"],
    ["Jenis Kelamin", "L untuk Laki-laki, P untuk Perempuan", "Ya"],
    ["Tempat Lahir", "Kota/kabupaten tempat lahir", "Opsional"],
    ["Tanggal Lahir", "Format DD/MM/YYYY contoh: 27/10/2009", "Opsional"],
    ["Agama", "Islam / Kristen / Katolik / Hindu / Buddha", "Opsional"],
    ["Kewarganegaraan", "WNI / WNA", "Opsional"],
    ["Anak Ke", "Urutan anak dalam keluarga (angka)", "Opsional"],
    ["Jumlah Saudara Kandung", "Jumlah saudara kandung (angka)", "Opsional"],
    ["Yatim/Piatu", "Tidak / Yatim / Piatu / Yatim Piatu", "Opsional"],
    ["Bahasa Sehari-hari", "Bahasa yang digunakan di rumah", "Opsional"],
    ["Dusun/Lingkungan", "Nama dusun/lingkungan tempat tinggal", "Opsional"],
    ["RT", "RT tempat tinggal, contoh: RT/01", "Opsional"],
    ["RW", "RW tempat tinggal, contoh: RW/01", "Opsional"],
    ["Desa/Kelurahan", "Nama desa/kelurahan", "Opsional"],
    ["Kecamatan", "Nama kecamatan", "Opsional"],
    ["Kabupaten/Kota", "Nama kabupaten atau kota", "Opsional"],
    ["No. HP Siswa", "Nomor HP siswa yang aktif", "Opsional"],
    ["No. HP Orang Tua", "Nomor HP orang tua yang aktif", "Opsional"],
    ["Tinggal Dengan", "Orang Tua / Wali / Kost / Asrama", "Opsional"],
    ["Jarak ke Sekolah", "Contoh: Kurang 1 Km / Lebih Dari 1 Km", "Opsional"],
    ["Golongan Darah", "A / B / AB / O", "Opsional"],
    ["Penyakit yang Pernah Diderita", "Riwayat penyakit", "Opsional"],
    ["Tinggi Badan", "Dalam satuan cm, contoh: 169", "Opsional"],
    ["Berat Badan", "Dalam satuan kg, contoh: 43", "Opsional"],
    ["Asal Sekolah", "Nama SMP/MTs asal", "Opsional"],
    ["Alamat Asal Sekolah", "Alamat lengkap sekolah asal", "Opsional"],
    ["Nomor Ijazah", "Nomor ijazah SMP/MTs", "Opsional"],
    ["Kode Jurusan", "Kode jurusan: TKJ / AK / ATU / DKV / DPIB", "Ya"],
    ["Tahun Masuk", "Tahun masuk SMK, contoh: 2025", "Opsional"],
    ["Tanggal Diterima", "Format DD/MM/YYYY", "Opsional"],
    ["Nama Ayah", "Nama lengkap ayah kandung", "Opsional"],
    ["NIK Ayah", "NIK ayah kandung", "Opsional"],
    ["Tempat Lahir Ayah", "Kota tempat lahir ayah", "Opsional"],
    ["Tanggal Lahir Ayah", "Format DD/MM/YYYY", "Opsional"],
    ["Pendidikan Ayah", "SD / SMP / SMA / D3 / S1 / S2 / dll.", "Opsional"],
    ["Pekerjaan Ayah", "Pekerjaan ayah", "Opsional"],
    ["Nama Ibu", "Nama lengkap ibu kandung", "Opsional"],
    ["NIK Ibu", "NIK ibu kandung", "Opsional"],
    ["Tempat Lahir Ibu", "Kota tempat lahir ibu", "Opsional"],
    ["Tanggal Lahir Ibu", "Format DD/MM/YYYY", "Opsional"],
    ["Pendidikan Ibu", "SD / SMP / SMA / D3 / S1 / S2 / dll.", "Opsional"],
    ["Pekerjaan Ibu", "Pekerjaan ibu", "Opsional"],
    ["Nama Wali", "Nama wali (jika bukan orang tua)", "Opsional"],
    ["Pekerjaan Wali", "Pekerjaan wali", "Opsional"],
    ["Status", "AKTIF / LULUS / KELUAR / PINDAH (default: AKTIF)", "Opsional"],
    ["Keterangan", "Catatan tambahan", "Opsional"],
    [""],
    ["CATATAN:"],
    ["- Baris pertama adalah header, jangan dihapus"],
    ["- Baris kedua adalah contoh data, hapus sebelum import"],
    ["- NIS yang sudah ada di sistem akan diperbarui (update)"],
    ["- NIS baru akan membuat akun siswa baru otomatis"],
  ];
  const wsPetunjuk = XLSX.utils.aoa_to_sheet(petunjukData);
  wsPetunjuk["!cols"] = [{ wch: 30 }, { wch: 55 }, { wch: 15 }];
  XLSX.utils.book_append_sheet(wb, wsPetunjuk, "Petunjuk");

  const buf = XLSX.write(wb, { type: "buffer", bookType: "xlsx" });
  return new NextResponse(buf, {
    headers: {
      "Content-Type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "Content-Disposition": 'attachment; filename="template-buku-induk-siswa.xlsx"',
    },
  });
}
